services:
  radarr-mcp:
    build: .
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: radarr-mcp
    restart: unless-stopped
    ports:
      - "${RADARR_MCP_PORT:-9170}:9170"
    env_file:
      - .env
    volumes:
      - /mnt/cache/appdata/radarr-mcp/logs:/app/logs:rw
    networks:
      - jakenet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9170/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  jakenet:
