services:
  radarr-mcp:
    build: .
    labels:
      - com.centurylinklabs.watchtower.enable=false
    container_name: radarr-mcp
    restart: unless-stopped
    ports:
      - "${RADARR_MCP_PORT:-4200}:4200"
    environment:
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_MCP_HOST=0.0.0.0
      - RADARR_MCP_PORT=4200
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RADARR_NAME=${RADARR_NAME:-radarr}
    volumes:
      - /mnt/cache/appdata/radarr-mcp/logs:/app/logs:rw
    networks:
      - jakenet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  jakenet:
